/**
 * Astro Integration: RAG Index Generator
 * 
 * Generates RAG index at build time
 * Story 10.1: Build-Time RAG Content Preparation
 * 
 * This integration ensures RAG index files are generated and available in dist/
 * during the build process. It works by:
 * 1. Checking if files exist in public/rag-index/ (generated by prerendered endpoint)
 * 2. Copying them to dist/rag-index/ (Astro should do this automatically, but we ensure it)
 * 3. Verifying files are present in dist/ before build completes
 */

import type { AstroIntegration } from 'astro';

export default function ragIndexIntegration(): AstroIntegration {
  return {
    name: 'rag-index-generator',
    hooks: {
      'astro:build:done': async ({ dir, logger }) => {
        try {
          logger.info('🔍 Verifying RAG index files are in dist/...');
          
          const { copyFile, mkdir, readdir, access, constants } = await import('fs/promises');
          const { join } = await import('path');
          const { fileURLToPath } = await import('url');
          
          const publicDir = join(process.cwd(), 'public', 'rag-index');
          const distPath = fileURLToPath(dir);
          const distDir = join(distPath, 'rag-index');
          
          // Check if files exist in public/ first
          let publicFiles: string[] = [];
          try {
            publicFiles = await readdir(publicDir);
            publicFiles = publicFiles.filter(f => f.endsWith('.json'));
          } catch (error) {
            logger.warn('⚠️  RAG index files not found in public/rag-index/.');
            logger.warn('   The prerendered endpoint may not have run. Checking dist/...');
          }
          
          // Check if files already exist in dist/ (Astro should copy them automatically)
          let distFiles: string[] = [];
          try {
            distFiles = await readdir(distDir);
            distFiles = distFiles.filter(f => f.endsWith('.json'));
          } catch (error) {
            // dist/rag-index/ doesn't exist yet, we'll create it
          }
          
          // If files exist in public/ but not in dist/, copy them
          if (publicFiles.length > 0) {
            // Ensure dist directory exists
            await mkdir(distDir, { recursive: true });
            
            let copiedCount = 0;
            for (const file of publicFiles) {
              const sourcePath = join(publicDir, file);
              const destPath = join(distDir, file);
              
              // Only copy if file doesn't exist in dist/ or is newer
              try {
                await access(destPath, constants.F_OK);
                // File exists, skip (Astro already copied it)
              } catch {
                // File doesn't exist, copy it
                await copyFile(sourcePath, destPath);
                copiedCount++;
              }
            }
            
            if (copiedCount > 0) {
              logger.info(`✅ Copied ${copiedCount} RAG index file(s) to dist/`);
            }
          }
          
          // Final verification: check if manifest.json exists in dist/
          const manifestPath = join(distDir, 'manifest.json');
          try {
            await access(manifestPath, constants.F_OK);
            logger.info('✅ RAG index manifest.json verified in dist/');
          } catch (error) {
            logger.error('❌ RAG index manifest.json NOT found in dist/rag-index/');
            logger.error('   This will cause 404 errors in production.');
            logger.error('   Files should be in: ' + distDir);
            
            // List what's actually in dist/rag-index/ for debugging
            try {
              const actualFiles = await readdir(distDir);
              logger.error('   Files found in dist/rag-index/: ' + actualFiles.join(', '));
            } catch (e) {
              logger.error('   dist/rag-index/ directory does not exist');
            }
            
            // Don't throw - allow build to complete, but log the error clearly
            throw new Error('RAG index files are missing from dist/. The prerendered endpoint may not have executed during build.');
          }
          
          // Verify at least one post index exists
          const postIndexes = distFiles.filter(f => f !== 'manifest.json' && f.endsWith('.json'));
          if (postIndexes.length === 0 && publicFiles.length > 0) {
            logger.warn('⚠️  No post index files found in dist/, but they exist in public/.');
            logger.warn('   This might indicate a build timing issue.');
          } else if (postIndexes.length > 0) {
            logger.info(`✅ Found ${postIndexes.length} post index file(s) in dist/`);
          }
          
        } catch (error) {
          logger.error(`❌ Error verifying RAG index files: ${error instanceof Error ? error.message : String(error)}`);
          // Don't throw - allow build to complete even if verification fails
          // But log it clearly so it's visible in build logs
          logger.warn('⚠️  Build will continue but RAG index files may not be available in production');
        }
      },
    },
  };
}
